services:
  nginx_ssl_proxy:
    image: nginx:1.27-alpine
    restart: unless-stopped
    volumes:
      - ./app.conf:/etc/nginx/conf.d/default.conf
      - ./kobo.local-key.pem:/etc/certs/kobo.local-key.pem:ro
      - ./kobo.local-cert.pem:/etc/certs/kobo.local-cert.pem:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      kobo-fe-network:
        aliases:
          - nginx_ssl_proxy

networks:
  kobo-fe-network:
    name: kobofe_kobo-fe-network
    external: true
